config/routes.rb
Computronix::Application.routes.draw do


  get "/payments/new/:payment_id", to: "payments#new", as: 'one_click_buy'
  get "/shop_category/:category_id", to: "front_page#index", as: 'nav'
  get '/setup', to: "setup#index"

  get '/cart', to: 'carts#index', as: 'cart'
  resource :carts, only: [:index,:update,:new,:destroy] do
    get '/', to: "carts#index"
  end


  resources :payments do
    collection do
      get 'execute'
      get 'cancel'
      post 'new', as: 'new'
    end
  end
  resources :sales do
    collection do
      get 'cancel'
      get 'success'
    end
  end

  resources :product

  resources :categories do
    resources :products
  end

  root to: "front_page#index"
end

app/controllers/front_page_controller.rb
require 'paypal-sdk-rest'
class FrontPageController < ApplicationController
  include PayPal::SDK::REST

  def index
    @category = Category.find(params[:category_id]) if params[:category_id]
    @currency = params[:currency]|| :GBP
  end


end

app/helpers/front_page_helper.rb
require 'money'
require 'money/bank/google_currency'
require 'json'

module FrontPageHelper

  def nav_button_class tree_level

    "class='nav button nav_#{css_class(tree_level)}'".html_safe
  end

  def css_class tree_level
    return "root" if tree_level == 1
    return "major" if tree_level == 2
    return "minor" if tree_level == 3
  end

  def tree_pos tree_level
    temp = ""
    for i in 2..tree_level do
      temp += "━"
    end
    "╰#{temp}┫"
  end

  def nav_locals
    {categories: Category.roots, tree_level: 0}
  end

  def center_page_locals
    {categories: (@category || Category.roots)}
  end

  def set_visibility category, tree_level
    "setVisibility(nav button nav_#{css_class(tree_level + 1)}, \"block\" )"
  end


end

app/views/front_page/_images.html.erb
<% if product.images %>
  <% product.all_images.each do |image| %>
    <%= image_tag(image[0] ,alt: image[1],class:'image',size: image[2] )%>
  <% end %>
<% end %>

app/views/front_page/_nav.html.erb
<% tree_level += 1 %>
<% categories.each do |category| %>
  <li <%= nav_button_class(tree_level) %> id=<%= "#nav_#{tree_level}"%>>
    <%= link_to "#{tree_pos(tree_level)}#{category.title}", nav_path(category), onclick: set_visibility(category, tree_level) %></li>
  <%= render "nav", categories: category.children,tree_level: tree_level   %>
<% end %>

app/views/front_page/_product.html.erb
<section class='infomation'>
  <section class='specification'>
    <div class='title'>
      <%= "Product: #{product.title}" %>
    </div>
    <figure class='images'>
      <%= render 'images', product: product %>
    </figure>
    <div class='description'>
      <%= "Description:
      #{product.description}" %>
    </div>
  </section>
  <section class='attributes'>
    <div class='value'>
      <%= "Value(#{currency}):#{currency_format_for product.value}" %>
    </div>
    <div class='stock'>
      <%= "Stock Level:#{product.stock}" %>
    </div>
    <section class='actions'>
      <div class='button buy-paypal'>
        <%= link_to 'One click checkout with Paypal', new_payments_path(product_id: product.id), method: :post %>
      </div>
      <div class='input quanity'>
        <%= form_tag(carts_path,method: :patch,) do %>
          <%= text_field_tag 'quantity', 1, maxlength: 2 %>
          <%= hidden_field_tag 'product_id', product.id %>
          <%= submit_tag "Add to cart", class: 'button add-to-cart' %>
        <% end %>
      </div>
    </section>
  </section>
</section>

app/views/front_page/_shelf.html.erb
<section class='shelf'>
<h1><%= @category ? @category.title : "All Items" %></h1>
<% Array(categories).flatten.each do |category| %>
  <% Array(category.all_products).flatten.each do |product| %>
    <article class='product'>
      <%= render 'product',product: product,currency: currency %>
    </article>
  <% end %>
<% end %>
</section>

app/views/front_page/index.html.erb
<%= render 'shelf', center_page_locals%>