config/routes.rb
Computronix::Application.routes.draw do


  get "/payments/new/:payment_id", to: "payments#new", as: 'one_click_buy'
  get "/shop_category/:category_id", to: "front_page#index", as: 'nav'
  get '/setup', to: "setup#index"

  get '/cart', to: 'carts#index', as: 'cart'
  resource :carts, only: [:index,:update,:new,:destroy] do
    get '/', to: "carts#index"
  end


  resources :payments do
    collection do
      get 'execute'
      get 'cancel'
      post 'new', as: 'new'
    end
  end
  resources :sales do
    collection do
      get 'cancel'
      get 'success'
    end
  end

  resources :product

  resources :categories do
    resources :products
  end

  root to: "front_page#index"
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :cart?, only: [:new]

  def index
  end

  def update
    if params[:product_id].is_a?(Array)
      cart =[]
      product_ids = params[:product_id]
      quant = params[:quantity].each {|q| q = q.to_i}
      product_ids.each_with_index do |id,i|
        if quant[i].to_i < 1
        else
          cart.push({id:id, quantity: quant[i]})
        end
      end
    else
      cart = session[:cart]
      quantity = params[:quantity].to_i
      id = params[:product_id]
      add_to_cart = true
      cart.each do |product|
        if product[:id] == id
          quant = product[:quantity].to_i #this is here becuase I kept getting 'undefined method `to_i=' for "1":String', this fixes it
          quant += quantity
          product[:quantity] = quant.to_s
          add_to_cart = false
        end
      end
      if add_to_cart
        cart.push({id: id,quantity: quantity})
      end
    end
    session[:cart] = cart
    redirect_to :back
  end

  def new
    session[:cart] = []
    redirect_to :root
  end

  def destroy
    new
  end

  private

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/carts/_small_cart.html.erb
<section class='small-cart'>
  <section class='table'>
  <table>
    <thead>
      <th>Name</th>
      <th>Quanity</th>
      <th>Total Value<%= "\n(#{currency})" %></th>
    </thead>
    <tbody>
      <% cart.each do |product| %>
        <% product_model = Product.find(product[:id]) %>
        <% quant = product[:quantity]  %>
        <tr>
          <td>
          <%= product_model.title %>
          </td>
          <td>
            <%= quant %>
          </td>
          <td>
            <%=  "#{currency_format_for (product_model.value * quant.to_i) }"%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </section>
  <section class='actions'>
    <%= link_to 'Go to Cart', cart_path, class: 'button cart' %>
    <%= link_to 'Clear Cart', carts_path, class: 'button cart', method: :delete %>
  </section>
</section>

app/views/carts/index.html.erb
<h1>Cart</h1>
<p></p>
<table>
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Quantity</th>
      <th>Value(GBP)</th>
      <th>Line total(GBP)</th>
    </tr>
  </thead>
  <tbody>
    <%= form_tag(carts_path,method: :patch,) do %>
      <% total_value = 0 %>
      <% cart.each do |product| %>
        <% id = product[:id] %>
        <% product_model = Product.find(id) %>
        <% quant = product[:quantity].to_i %>
        <tr>
          <%= hidden_field_tag "product_id[]", product_model.id %>
          <td>
            <%= label_tag product_model.title %>
          </td>
          <td>
          <%= text_field_tag 'quantity[]', quant, maxlength: 2 %>
          </td>
          <td>
            <%= label_tag "#{currency_format_for product_model.value}" %>
          </td>
          <% product_total_value = product_model.value.to_f * quant %>
          <td><%= label_tag "#{currency_format_for product_total_value}" %>
          </td>
          <% total_value += product_total_value %>
        </tr>
      <% end %>
      <tr>
        <td></td>
        <td></td>
        <td>Total Value(GBP):</td>
        <td><%= currency_format_for total_value %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= submit_tag "Update Cart", class: 'button update-cart' %></td>
        <td></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>