config/routes.rb
Computronix::Application.routes.draw do


  get "/payments/new/:payment_id", to: "payments#new", as: 'one_click_buy'
  get "/shop_category/:category_id", to: "front_page#index", as: 'nav'
  get '/setup', to: "setup#index"

  get '/cart', to: 'carts#index', as: 'cart'
  resource :carts, only: [:index,:update,:new,:destroy] do
    get '/', to: "carts#index"
  end


  resources :payments do
    collection do
      get 'execute'
      get 'cancel'
      post 'new', as: 'new'
    end
  end
  resources :sales do
    collection do
      get 'cancel'
      get 'success'
    end
  end

  resources :product

  resources :categories do
    resources :products
  end

  root to: "front_page#index"
end

app/models/category.rb
class Parentage < ActiveModel::Validator
 def validate(record)
  if record.ancestors.length > 2
    record.errors[:base] << "Can't have more then two ancestors"
  end
 end
end
class Category < ActiveRecord::Base

  has_many :products

  has_many :children, class_name: 'Category', foreign_key: 'parent_id', dependent: :destroy
  belongs_to :parent, class_name: 'Category'
  validates_with Parentage

  scope :roots, -> {where(parent_id: nil)}

  def ancestors
    @ancestors ||= [parent,parent.try(:ancestors)].flatten.compact
  end

  def all_children
    @all_children ||= [self,children,children.map{|child| child.all_children}].flatten.compact
  end

  def all_products
    @all_products ||= Product.where(category_id: all_children)
  end

  def root
    @root ||= ancestors.last
  end

  def root?
    self.parent.nil?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category, only: [:show, :edit, :update, :destroy]
  before_filter :protect

  def index
    @category = nil
    @categories = Category.where( parent_id: nil )

  end

  def show
    @category = Category.find(params[:id])
    @categories = @category.children
    render :action => :index
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.parent = Category.find(params[:id]) unless params[:id].nil?
    if @category.save
      redirect_to @category, notice: "category(#{@category.title}) was successfully created."
    else
      render action: 'new'
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Competition was successfully updated.'
    else
      render action: 'edit'
    end
  end
  def destroy
    @category = load_category
    parent = @category.parent
    if @category.destroy
      redirect_to parent || :root
    end
  end

  private

    def load_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def child?
    @category && !@category.parent.nil?
  end

  def first_child_catagory?
    @category.parent.nil? ? :categories : @category.parent
  end

end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='title'>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class='actions'>
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit catagory</h1>
<%= render 'form' %>
<div>
  <% if child? %>
     <%= link_to 'back', @category.parent %>
   <% else %>
     <%= link_to 'back', :categories %>
   <% end %>
</div>

app/views/categories/index.html.erb
<h1><%= @category.nil? ? 'Main categories' : @category.title %></h1>
<section class='bar'>
  <% if child? %>
    <%= link_to 'back', first_child_catagory? if child? %> | <%= link_to 'new sub-category', new_category_path(@category) if @category.ancestors.length < 3 %>
  <% else %>
  <%= link_to 'back', :setup %> |
    <%= link_to 'new root-category', [:new, :category] %>
  <% end %>
</section>
<table>
  <% @categories.each do |category| %>
  <tr>
    <td><%= link_to category.title, category_path(category) %></td>
    <td><%= link_to 'Edit', [:edit,category] %></td>
    <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure? this will also delete all child catagories'}%></td>
  </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h1>New catagory</h1>
<%= render 'form' %>
<div>
  <% if child? %>
    <%= link_to 'back', @category.parent %>
  <% else %>
    <%= link_to 'back', :categories %>
  <% end %>
</div>